{{- if .Values.centralBackend.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "d4d.fullname" . }}-central-backend
  labels:
    {{- include "d4d.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.centralBackend.apiKey | quote }}
{{- end }}
