apiVersion: v1
kind: Service
metadata:
  name: {{ include "d4d.fullname" . }}-central-backend
  labels:
    {{- include "d4d.labels" . | nindent 4 }}
    app.kubernetes.io/component: central-backend
spec:
  type: {{ .Values.centralBackend.service.type }}
  selector:
    {{- include "d4d.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: central-backend
  ports:
    - name: http
      port: {{ .Values.centralBackend.service.port }}
      targetPort: 8000
      {{- if and (eq .Values.centralBackend.service.type "NodePort") .Values.centralBackend.service.nodePort }}
      nodePort: {{ .Values.centralBackend.service.nodePort }}
      {{- end }}
