apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "d4d.fullname" . }}-edge-simulator
  labels:
    {{- include "d4d.labels" . | nindent 4 }}
data:
  CENTRAL_WS_BASE_URL: "ws://{{ include "d4d.fullname" . }}-central-backend:{{ .Values.centralBackend.service.port }}"
  NUM_EDGES: {{ .Values.edgeSimulator.numEdges | quote }}
